### ISSUE TITLE
[Bug] Using ServiceUI.exe from Microsoft Deployment Kit (MDT) removes the user right to create symbolic links in Windows

### ISSUE THREAD

**Issue by JonasNjopOlsson** [PSAppDeployToolkit/PSAppDeployToolkit#1053]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

_This is not a bug report for PSAppDeployToolkit itself but rather information regarding issues introduced by the **ServiceUI.exe** utility described below._

We are using **ServiceUI.exe** from the Microsoft Deployment Toolkit (MDT) to display dialogs and other information to users when deploying application packages using Microsoft Intune and PSADT. We are following the example instructions included in PSADT at https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/main/Examples/ServiceUI and it works well in our client environment, which is based on Windows 10 and Windows 11.

However, we encountered issues when deploying SQL Server 2017 and its Machine Learning component, which includes integrated installations of the languages R and Python. The installations of these languages, which is performed from the SQL Server setup program, includes running a small, bundled executable, **RegisterRExt.exe**, which sets up the integration between the languages and the SQL Server Database Engine service. One of the tasks performed by RegisterRExt.exe includes creating **symbolic links** in the SQL Server installation directory, in subdirectories below "C:\Program Files" on the client.

When deploying the SQL Server package using Intune + ServiceUI.exe + PSADT, we always encountered an error in the installation process when reaching the step where symbolic links were supposed to be created. An example of the logged error output from the RegisterRExt.exe command (sorry for the system messages in Swedish):

```
 Information: 0 : Working Directory Name is "C:\Program Files\Microsoft SQL Server\MSSQL14.INSTANCENAME\PYTHON_SERVICES.3.7\..\MSSQL\ExtensibilityData".
    DateTime=xxxxxxx
 Error: 0 : System.Exception: Exception occurred in Settings Install ---> System.Exception: Couldnt create the symbolic link for ExtensibilityData ---> System.InvalidOperationException: Failed to create symbolic link with 2 error
   at Microsoft.SqlServer.Server.Settings.CreateDirectoryLink(String symLinkName, String targetName, Boolean isHidden)
   at Microsoft.SqlServer.Server.Settings.CreateSymbolicLink(String instanceName, String instancePath, String targetName, String targetPath, Boolean isXcopyInstall, ScriptTypeEnum scriptType)
   --- Slut på stackspårning för interna undantag ---
   at Microsoft.SqlServer.Server.Settings.CreateSymbolicLink(String instanceName, String instancePath, String targetName, String targetPath, Boolean isXcopyInstall, ScriptTypeEnum scriptType)
   at Microsoft.SqlServer.Server.Settings..ctor(ParsedArguments parsedArgs, String instancePath, Boolean isXcopyInstall, Boolean isAppContainerEnabled, String sqlExtDataPath)
   at Microsoft.SqlServer.Server.Settings.Install(ParsedArguments parsedArgs, String binnPath, Boolean isXcopyInstall, FileSecurity fileSecurity)
   --- Slut på stackspårning för interna undantag ---
   at Microsoft.SqlServer.Server.Settings.Install(ParsedArguments parsedArgs, String binnPath, Boolean isXcopyInstall, FileSecurity fileSecurity)
   at Microsoft.SqlServer.Server.Program.Main(String[] args)
    DateTime=xxxxxxx
 Information: 0 : Failed to complete the operation successfully.
    DateTime=xxxxxxx
```

Since the error only occurred when deploying from Intune and not when deploying manually from a Command Prompt, either running as a local administrator account or as the local NT AUTHORITY\SYSTEM account, we surmised that something must be amiss with the Intune environment.

After further testing and verification we discovered that the deployment script was able to complete successfully when run directly from Intune but only when running silently, without any user interaction through the involvement of **ServiceUI.exe**.

We verified our findings by comparing the user rights assigned to different Command Prompt processes, either running directly as NT AUTHORITY\SYSTEM or started by ServiceUI.exe (by the SYSTEM account). See detailed steps to reproduce below.

When comparing the privileges assigned to the two processes, we could see that even though both processes were running as SYSTEM, the process spawned by ServiceUI.exe was missing several privileges:

- SeCreatePagefilePrivilege (Create a pagefile)
- SeCreateSymbolicLinkPrivilege (Create symbolic links)
- SeDelegateSessionUserImpersonatePrivilege (Obtain an impersonation token for another user in the same session)
- SeIncreaseWorkingSetPrivilege (Increase a process working set)
- SeLockMemoryPrivilege (Lock pages in memory)
- SeSystemProfilePrivilege (Profile system performance)
- SeSystemtimePrivilege (Change the system time)
- SeTimeZonePrivilege (Change the time zone)

The missing privilege **SeCreateSymbolicLinkPrivilege** was the root cause of the issues we encountered when installing SQL Server 2017 with Machine Learning.

The workaround we employed was to stop using **ServiceUI.exe** for the package in question and deploy it silently instead.

### Steps to reproduce

1. Start an interactive Command Prompt in the SYSTEM context using PSExec from Sysintenals (https://learn.microsoft.com/en-us/sysinternals/downloads/psexec).
2. From that Command Prompt, start an additional prompt using ServiceUI: ```ServiceUI.exe -nowait -process:explorer.exe C:\Windows\System32\cmd.exe```
3. In both prompts, run the builtin command **whoami /all**
4. Compare the contents of the section **PRIVILEGES INFORMATION**

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : sv-SE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment]
We've got something in play that should alleviate issues like this, but it might not be there for the initial v4 release. I'm going to place it on hold for now, but will come back to you as things develop further in this space.

**Comment by mjr4077au** [comment]
This issue will be resolved by way of completion of https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1, which is coming soon.
