### ISSUE TITLE
[Bug] Get-ADTShortcut variable $Path cannot be retrieved

### ISSUE THREAD

**Issue by MarkRouleau** [PSAppDeployToolkit/PSAppDeployToolkit#1210]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.4

### Describe the bug

Running Get-ADTShortcut returns the following error: `Error Inner Exception(s):
-------------------------

Message : The variable '$Path' cannot be retrieved because it has not been set.
[2024-12-20 08:26:19.462] [Install] [Show-ADTDialogBox] [Info] :: Displaying Dialog Box with message: Error Record:
-------------

Message               : Cannot validate argument on parameter 'Path'. The variable '$Path' cannot be retrieved because it has not been set.
InnerException        : System.Management.Automation.RuntimeException: The variable '$Path' cannot be retrieved because it has not been set.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
                           at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)       

FullyQualifiedErrorId : ParameterArgumentValidationError,Get-ADTShortcut
ScriptStackTrace      : at Install-ADTDeployment, C:\Users\Rouleaum\Desktop\Test\PSAppDeployToolkit_4.0.4\Invoke-AppDeployToolkit.ps1: line 151
                        at <ScriptBlock>, C:\Users\Rouleaum\Desktop\Test\PSAppDeployToolkit_4.0.4\Invoke-AppDeployToolkit.ps1: line 307
                        at <ScriptBlock>, <No file>: line 1

PositionMessage       : At C:\Users\Rouleaum\Desktop\Test\PSAppDeployToolkit_4.0.4\Invoke-AppDeployToolkit.ps1:151 char:23
                        + ... rtcut -Path 'C:\users\rouleaum\desktop\Configuration Manager - Shortc ...
                        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------

Message : The variable '$Path' cannot be retrieved because it has not been set....
[2024-12-20 08:26:23.930] [Install] [Show-ADTDialogBox] [Info] :: Dialog Box Response: OK
[2024-12-20 08:26:23.998] [Finalization] [Close-ADTInstallationProgressFluent] [Info] :: Closing the installation progress dialog.
[2024-12-20 08:26:24.039] [Finalization] [Close-ADTSession] [Error] :: [PSAppDeployToolkit_4.0.4_EN_01] install completed with exit code [60001].
[2024-12-20 08:26:24.041] [Finalization] [Close-ADTSession] [Info] :: *******************************************************************************`

### Steps to reproduce

1. In powershell, execute Get-ADTShortcut -path 'C:\users\username\desktop\nameofshortcut.lnk'
2. Confirmed it also fails with the same error if run inside a newly created Invoke-AppDeployToolkit.ps1 script.
3.

### Environment data

```console
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile


Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mjr4077au** [comment]
Thanks for the report! This is fixed in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/2e7766bf18b53147a0252784dacde0f23f4238d1 and will be in the next point release.
