### ISSUE TITLE
Cannot Stop Service

### ISSUE THREAD

**Issue by cmschube** [PSAppDeployToolkit/PSAppDeployToolkit#197]
Trying to Use Stop-ServiceAndDependancies and Start-ServiceAndDependancies or Start-Service and Stop-Service

Both give the below error..

It's running into an error like the script isn't running as administrator "running from a "Run As Adminstrator" PowerShell console

If I run Stop-Service from a normal said Run As Administrator PowerShell Console, it stops/starts just fine. 

```
 [08-01-2016 15:15:30.629] [Installation] [Stop-ServiceAndDependencies] :: Failed to stop the service [McShield].
Error Record:
-------------

Message        : Service 'McAfee McShield (McShield)' cannot be stopped due to the following error: Cannot open
                 McShield service on computer 'MININT-VHN8CB6'.
InnerException : System.InvalidOperationException: Cannot open McShield service on computer 'MININT-VHN8CB6'. --->
                 System.ComponentModel.Win32Exception: Access is denied
                    --- End of inner exception stack trace ---
                    at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
                    at System.ServiceProcess.ServiceController.Stop()
                    at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStopService(ServiceController
                 serviceController, Boolean force, Boolean waitForServiceToStop)

FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand
ScriptStackTrace      : at Stop-ServiceAndDependencies<Process>,
                        \\crp24545\mdt$\Applications\MVSE8.8\AppDeployToolkit\AppDeployToolkitMain.ps1: line 9532
                        at <ScriptBlock>, \\crp24545\mdt$\Applications\MVSE8.8\Deploy-Application.ps1: line 137
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At \\crp24545\mdt$\Applications\MVSE8.8\AppDeployToolkit\AppDeployToolkitMain.ps1:9532 char:50
                  + ... ]$Service = Stop-Service -InputObject (Get-Service -ComputerName $Com ...
                  +           



Error Inner Exception(s):
-------------------------

Message        : Cannot open McShield service on computer 'MININT-VHN8CB6'.
InnerException : System.ComponentModel.Win32Exception (0x80004005): Access is denied


Message        : Access is denied
InnerException :


```

**Comment by cmschube** [comment]
Disregard. Uncheck "Prevent McAfee Services fom being Stopped" in the Access Protection.
